LANGUAGE_MAPPING = {
    "yoruba": "yoruba",
    "igbo": "igbo",
    "swahili": "swahili",
    "hausa": "hausa",
    "ijaw": "ijaw",
    "afrikaans": "afrikaans",
    "idoma": "idoma",
    "zulu": "zulu",
    "setswana": "setswana",
    "twi": "twi",
    "isizulu": "zulu",
    "igala": "igala",
    "izon": "izon",
    "kiswahili": "swahili",
    "ebira": "ebira",
    "luganda": "luganda",
    "urhobo": "urhobo",
    "nembe": "nembe",
    "ibibio": "ibibio",
    "pidgin": "pidgin",
    "luhya": "luhya",
    "kinyarwanda": "kinyarwanda",
    "xhosa": "xhosa",
    "tswana": "setswana",
    "esan": "esan",
    "alago": "alago",
    "tshivenda": "venda",
    "fulani": "fulani",
    "isoko": "isoko",
    "akan (fante)": "akan",
    "ikwere": "ikwere",
    "sepedi": "sepedi",
    "efik": "efik",
    "edo": "bini",
    "luo": "dholuo",
    "kikuyu": "kikuyu",
    "bekwarra": "bekwarra",
    "isixhosa": "xhosa",
    "hausa/fulani": "hausa/fulani",
    "epie": "epie",
    "isindebele": "ndebele",
    "venda and xitsonga": "venda and xitsonga",
    "sotho": "sotho",
    "akan": "akan",
    "nupe": "nupe",
    "anaang": "anaang",
    "english": "english",
    "afemai": "etsako",
    "shona": "shona",
    "eggon": "eggon",
    "luganda and kiswahili": "luganda and kiswahili",
    "ukwuani": "ukwuani",
    "sesotho": "sesotho",
    "benin": "bini",
    "kagoma": "gyong",
    "nasarawa eggon": "eggon",
    "tiv": "tiv",
    "south african english": "south african english",
    "borana": "borana",
    "swahili ,luganda ,arabic": "swahili ,luganda ,arabic",
    "ogoni": "ogoni",
    "mada": "mada",
    "bette": "bette",
    "berom": "berom",
    "bini": "bini",
    "ngas": "ngas",
    "etsako": "etsako",
    "okrika": "okrika",
    "venda": "venda",
    "siswati": "swati",
    "damara": "damara",
    "yoruba, hausa": "yoruba, hausa",
    "southern sotho": "sotho",
    "kanuri": "kanuri",
    "itsekiri": "itsekiri",
    "ekpeye": "ekpeye",
    "mwaghavul": "mwaghavul",
    "bajju": "bajju",
    "luo, swahili": "dholuo, swahili",
    "dholuo": "dholuo",
    "ekene": "ekene",
    "jaba": "jaba",
    "ika": "ika",
    "angas": "ngas",
    "ateso": "ateso",
    "brass": "brass",
    "ikulu": "ikulu",
    "eleme": "eleme",
    "chichewa": "chichewa",
    "oklo": "oklo",
    "meru": "meru",
    "agatu": "agatu",
    "okirika": "kirirke",
    "igarra": "Ebira",
    "ijaw(nembe)": "ijaw",
    "khana": "khana",
    "ogbia": "ogbia",
    "gbagyi": "gbagyi",
    "portuguese": "portuguese",
    "delta": "bini",
    "bassa": "bassa",
    "etche": "etche",
    "kubi": "kubi",
    "jukun": "jukun",
    "igbo and yoruba": "igbo and yoruba",
    "urobo": "urhobo",
    "kalabari": "kalabari",
    "ibani": "ibani",
    "obolo": "obolo",
    "idah": "igala",
    "bassa-nge/nupe": "bassa-nge/nupe",
    "yala mbembe": "mbembe",
    "eket": "ibibio",
    "afo": "afo",
    "ebiobo": "ibiobo",
    "nyandang": "nyandang",
    "ishan": "esan",
    "bagi": "Gbagyi",
    "estako": "etsako",
    "gerawa": "gerawa",
}

accents_lang_families_dict = {
    "yoruba": "Niger-Congo",
    "igbo": "Niger-Congo",
    "swahili": "Niger-Congo",
    "hausa": "Afro-Asiatic",
    "ijaw": "Niger-Congo",
    "afrikaans": "Nilo-Saharan",
    "idoma": "Niger-Congo",
    "zulu": "Niger-Congo",
    "setswana": "Niger-Congo",
    "twi": "Niger-Congo",
    "isizulu": "Niger-Congo",
    "igala": "Niger-Congo",
    "izon": "Niger-Congo",
    "kiswahili": "Niger-Congo",
    "ebira": "Niger-Congo",
    "luganda": "Niger-Congo",
    "urhobo": "Niger-Congo",
    "nembe": "Niger-Congo",
    "ibibio": "Niger-Congo",
    "pidgin": "Afro-Asiatic",
    "luhya": "Niger-Congo",
    "kinyarwanda": "Niger-Congo",
    "xhosa": "Niger-Congo",
    "tswana": "Niger-Congo",
    "esan": "Niger-Congo",
    "alago": "Niger-Congo",
    "tshivenda": "Niger-Congo",
    "fulani": "Niger-Congo",
    "isoko": "Niger-Congo",
    "akan (fante)": "Niger-Congo",
    "ikwere": "Niger-Congo",
    "sepedi": "Niger-Congo",
    "efik": "Niger-Congo",
    "edo": "Niger-Congo",
    "luo": "Nilo-Saharan",
    "kikuyu": "Niger-Congo",
    "bekwarra": "Niger-Congo",
    "isixhosa": "Niger-Congo",
    "hausa/fulani": "Afro-Asiatic",
    "epie": "Niger-Congo",
    "isindebele": "Niger-Congo",
    "venda and xitsonga": "Niger-Congo",
    "sotho": "Afro-Asiatic",
    "akan": "Niger-Congo",
    "nupe": "Niger-Congo",
    "anaang": "Niger-Congo",
    "english": "Niger-Congo",
    "afemai": "Niger-Congo",
    "shona": "Niger-Congo",
    "eggon": "Niger-Congo",
    "luganda and kiswahili": "Niger-Congo",
    "ukwuani": "Niger-Congo",
    "sesotho": "Niger-Congo",
    "benin": "Niger-Congo",
    "kagoma": "Niger-Congo",
    "nasarawa eggon": "Niger-Congo",
    "tiv": "Niger-Congo",
    "south african english": "Afro-Asiatic",
    "borana": "Afro-Asiatic",
    "swahili ,luganda ,arabic": "Niger-Congo",
    "ogoni": "Niger-Congo",
    "mada": "Niger-Congo",
    "bette": "Niger-Congo",
    "berom": "Niger-Congo",
    "bini": "Niger-Congo",
    "ngas": "Afro-Asiatic",
    "etsako": "Niger-Congo",
    "okrika": "Niger-Congo",
    "venda": "Niger-Congo",
    "siswati": "Niger-Congo",
    "damara": "Niger-Congo",
    "yoruba, hausa": "Niger-Congo",
    "southern sotho": "Afro-Asiatic",
    "kanuri": "Niger-Congo",
    "itsekiri": "Niger-Congo",
    "ekpeye": "Niger-Congo",
    "mwaghavul": "Afro-Asiatic",
    "bajju": "Afro-Asiatic",
    "luo, swahili": "Nilo-Saharan",
    "dholuo": "Nilo-Saharan",
    "ekene": "Niger-Congo",
    "jaba": "Niger-Congo",
    "ika": "Niger-Congo",
    "angas": "Afro-Asiatic",
    "ateso": "Nilo-Saharan",
    "brass": "Niger-Congo",
    "ikulu": "Niger-Congo",
    "eleme": "Niger-Congo",
    "chichewa": "Niger-Congo",
    "oklo": "Nilo-Saharan",
    "meru": "Afro-Asiatic",
    "agatu": "Niger-Congo",
    "okirika": "Niger-Congo",
    "igarra": "Niger-Congo",
    "ijaw(nembe)": "Niger-Congo",
    "khana": "Niger-Congo",
    "ogbia": "Niger-Congo",
    "gbagyi": "Niger-Congo",
    "portuguese": "Afro-Asiatic",
    "delta": "Niger-Congo",
    "bassa": "Niger-Congo",
    "etche": "Niger-Congo",
    "kubi": "Afro-Asiatic",
    "jukun": "Afro-Asiatic",
    "igbo and yoruba": "Niger-Congo",
    "urobo": "Niger-Congo",
    "kalabari": "Niger-Congo",
    "ibani": "Niger-Congo",
    "obolo": "Niger-Congo",
    "idah": "Niger-Congo",
    "bassa-nge/nupe": "Niger-Congo",
    "yala mbembe": "Niger-Congo",
    "eket": "Niger-Congo",
    "afo": "Nilo-Saharan",
    "ebiobo": "Niger-Congo",
    "nyandang": "Niger-Congo",
    "ishan": "Niger-Congo",
    "bagi": "Niger-Congo",
    "estako": "Niger-Congo",
    "gerawa": "Afro-Asiatic"
}

ACCENTS_COUNTRY_DICT = {
    'yoruba': 'NG',
    'igbo': 'NG',
    'swahili': 'KE',
    'ijaw': 'NG',
    'xhosa': 'ZA',
    'twi': 'GH',
    'luhya': 'KE',
    'igala': 'NG',
    'urhobo': 'NG',
    'hausa': 'NG',
    'kiswahili': 'KE',
    'zulu': 'ZA',
    'isizulu': 'ZA',
    'venda and xitsonga': 'ZA',
    'borana': 'KE',
    'afrikaans': 'ZA',
    'setswana': 'BW',
    'idoma': 'NG',
    'izon': 'NG',
    'chichewa': 'MW',
    'ebira': 'NG',
    'tshivenda': 'ZA',
    'isixhosa': 'ZA',
    'kinyarwanda': 'RW',
    'tswana': 'BW',
    'luganda': 'UG',
    'luo': 'KE',
    'venda': 'ZA',
    'dholuo': 'KE',
    'akan (fante)': 'GH',
    'sepedi': 'ZA',
    'kikuyu': 'KE',
    'isindebele': 'ZA',
    'luganda and kiswahili': 'UG',
    'akan': 'GH',
    'sotho': 'ZA',
    'south african english': 'ZA',
    'sesotho': 'ZA',
    'swahili ,luganda ,arabic': 'UG',
    'shona': 'ZW',
    'damara': 'NA',
    'southern sotho': 'ZA',
    'luo, swahili': 'KE',
    'ateso': 'UG',
    'meru': 'KE',
    'siswati': 'ZA',
    'portuguese': 'ZA',
    'esan': 'NG',
    'nasarawa eggon': 'NG',
    'ibibio': 'NG',
    'isoko': 'NG',
    'pidgin': 'NG',
    'alago': 'NG',
    'nembe': 'NG',
    'ngas': 'NG',
    'kagoma': 'NG',
    'ikwere': 'NG',
    'fulani': 'NG',
    'bette': 'NG',
    'efik': 'NG',
    'edo': 'NG',
    'hausa/fulani': 'NG',
    'bekwarra': 'NG',
    'epie': 'NG',
    'afemai': 'NG',
    'benin': 'NG',
    'nupe': 'NG',
    'tiv': 'NG',
    'okrika': 'NG',
    'etsako': 'NG',
    'ogoni': 'NG',
    'kubi': 'NG',
    'gbagyi': 'NG',
    'brass': 'NG',
    'oklo': 'NG',
    'ekene': 'NG',
    'ika': 'NG',
    'berom': 'NG',
    'jaba': 'NG',
    'itsekiri': 'NG',
    'ukwuani': 'NG',
    'yala mbembe': 'NG',
    'afo': 'NG',
    'english': 'NG',
    'ebiobo': 'NG',
    'igbo and yoruba': 'NG',
    'okirika': 'NG',
    'kalabari': 'NG',
    'ijaw(nembe)': 'NG',
    'anaang': 'NG',
    'eggon': 'NG',
    'bini': 'NG',
    'yoruba, hausa': 'NG',
    'ekpeye': 'NG',
    'bajju': 'NG',
    'kanuri': 'NG',
    'delta': 'NG',
    'khana': 'NG',
    'ogbia': 'NG',
    'mada': 'NG',
    'mwaghavul': 'NG',
    'angas': 'NG',
    'ikulu': 'NG',
    'eleme': 'NG',
    'igarra': 'NG',
    'etche': 'NG',
    'agatu': 'NG',
    'bassa': 'NG',
    'jukun': 'NG',
    'urobo': 'NG',
    'ibani': 'NG',
    'obolo': 'NG',
    'idah': 'NG',
    'eket': 'NG',
    'nyandang': 'NG',
    'estako': 'NG',
    'ishan': 'NG',
    'bassa-nge/nupe': 'NG',
    'bagi': 'NG',
    'gerawa': 'NG'
}

ACCENT_LANGUAGE_FAMILIES = {
    'yoruba': 'Niger-Congo',
    'igbo': 'Niger-Congo',
    'swahili': 'Niger-Congo',
    'hausa': 'Afro-Asiatic',
    'ijaw': 'Niger-Congo',
    'afrikaans': 'Germanic',
    'idoma': 'Niger-Congo',
    'zulu': 'Niger-Congo',
    'setswana': 'Niger-Congo',
    'twi': 'Niger-Congo',
    'isizulu': 'Niger-Congo',
    'igala': 'Niger-Congo',
    'izon': 'Niger-Congo',
    'kiswahili': 'Niger-Congo',
    'ebira': 'Niger-Congo',
    'luganda': 'Niger-Congo',
    'urhobo': 'Niger-Congo',
    'nembe': 'Niger-Congo',
    'ibibio': 'Niger-Congo',
    'pidgin': 'Afro-Asiatic',
    'luhya': 'Niger-Congo',
    'kinyarwanda': 'Niger-Congo',
    'xhosa': 'Niger-Congo',
    'tswana': 'Niger-Congo',
    'esan': 'Niger-Congo',
    'alago': 'Niger-Congo',
    'tshivenda': 'Niger-Congo',
    'fulani': 'Niger-Congo',
    'isoko': 'Niger-Congo',
    'akan (fante)': 'Niger-Congo',
    'ikwere': 'Niger-Congo',
    'sepedi': 'Niger-Congo',
    'efik': 'Niger-Congo',
    'edo': 'Niger-Congo',
    'luo': 'Nilo-Saharan',
    'kikuyu': 'Niger-Congo',
    'bekwarra': 'Niger-Congo',
    'isixhosa': 'Niger-Congo',
    'hausa/fulani': 'Afro-Asiatic',
    'epie': 'Niger-Congo',
    'isindebele': 'Niger-Congo',
    'venda and xitsonga': 'Niger-Congo',
    'sotho': 'Afro-Asiatic',
    'akan': 'Niger-Congo',
    'nupe': 'Niger-Congo',
    'anaang': 'Niger-Congo',
    'english': 'Niger-Congo',
    'afemai': 'Niger-Congo',
    'shona': 'Niger-Congo',
    'eggon': 'Niger-Congo',
    'luganda and kiswahili': 'Niger-Congo',
    'ukwuani': 'Niger-Congo',
    'sesotho': 'Niger-Congo',
    'benin': 'Niger-Congo',
    'kagoma': 'Niger-Congo',
    'nasarawa eggon': 'Niger-Congo',
    'tiv': 'Niger-Congo',
    'south african english': 'Afro-Asiatic',
    'borana': 'Afro-Asiatic',
    'swahili ,luganda ,arabic': 'Niger-Congo',
    'ogoni': 'Niger-Congo',
    'mada': 'Niger-Congo',
    'bette': 'Niger-Congo',
    'berom': 'Niger-Congo',
    'bini': 'Niger-Congo',
    'ngas': 'Afro-Asiatic',
    'etsako': 'Niger-Congo',
    'okrika': 'Niger-Congo',
    'venda': 'Niger-Congo',
    'siswati': 'Niger-Congo',
    'damara': 'Niger-Congo',
    'yoruba, hausa': 'Niger-Congo',
    'southern sotho': 'Afro-Asiatic',
    'kanuri': 'Niger-Congo',
    'itsekiri': 'Niger-Congo',
    'ekpeye': 'Niger-Congo',
    'mwaghavul': 'Afro-Asiatic',
    'bajju': 'Afro-Asiatic',
    'luo, swahili': 'Nilo-Saharan',
    'dholuo': 'Nilo-Saharan',
    'ekene': 'Niger-Congo',
    'jaba': 'Niger-Congo',
    'ika': 'Niger-Congo',
    'angas': 'Afro-Asiatic',
    'ateso': 'Nilo-Saharan',
    'brass': 'Niger-Congo',
    'ikulu': 'Niger-Congo',
    'eleme': 'Niger-Congo',
    'chichewa': 'Niger-Congo',
    'oklo': 'Nilo-Saharan',
    'meru': 'Afro-Asiatic',
    'agatu': 'Niger-Congo',
    'okirika': 'Niger-Congo',
    'igarra': 'Niger-Congo',
    'ijaw(nembe)': 'Niger-Congo',
    'khana': 'Niger-Congo',
    'ogbia': 'Niger-Congo',
    'gbagyi': 'Niger-Congo',
    'portuguese': 'Romance',
    'delta': 'Niger-Congo',
    'bassa': 'Niger-Congo',
    'etche': 'Niger-Congo',
    'kubi': 'Afro-Asiatic',
    'jukun': 'Afro-Asiatic',
    'igbo and yoruba': 'Niger-Congo',
    'urobo': 'Niger-Congo',
    'kalabari': 'Niger-Congo',
    'ibani': 'Niger-Congo',
    'obolo': 'Niger-Congo',
    'idah': 'Niger-Congo',
    'bassa-nge/nupe': 'Niger-Congo',
    'yala mbembe': 'Niger-Congo',
    'eket': 'Niger-Congo',
    'afo': 'Nilo-Saharan',
    'ebiobo': 'Niger-Congo',
    'nyandang': 'Niger-Congo',
    'ishan': 'Niger-Congo',
    'bagi': 'Niger-Congo',
    'estako': 'Niger-Congo',
    'gerawa': 'Afro-Asiatic',
}
