LANGUAGE_MAPPING = {
    "yoruba": "yoruba",
    "igbo": "igbo",
    "swahili": "swahili",
    "hausa": "hausa",
    "ijaw": "ijaw",
    "afrikaans": "afrikaans",
    "idoma": "idoma",
    "zulu": "zulu",
    "setswana": "setswana",
    "twi": "twi",
    "isizulu": "zulu",
    "igala": "igala",
    "izon": "izon",
    "kiswahili": "swahili",
    "ebira": "ebira",
    "luganda": "luganda",
    "urhobo": "urhobo",
    "nembe": "nembe",
    "ibibio": "ibibio",
    "pidgin": "pidgin",
    "luhya": "luhya",
    "kinyarwanda": "kinyarwanda",
    "xhosa": "xhosa",
    "tswana": "setswana",
    "esan": "esan",
    "alago": "alago",
    "tshivenda": "venda",
    "fulani": "fulani",
    "isoko": "isoko",
    "akan (fante)": "akan",
    "ikwere": "ikwere",
    "sepedi": "sepedi",
    "efik": "efik",
    "edo": "bini",
    "luo": "dholuo",
    "kikuyu": "kikuyu",
    "bekwarra": "bekwarra",
    "isixhosa": "xhosa",
    "hausa/fulani": "hausa/fulani",
    "epie": "epie",
    "isindebele": "ndebele",
    "venda and xitsonga": "venda and xitsonga",
    "sotho": "sotho",
    "akan": "akan",
    "nupe": "nupe",
    "anaang": "anaang",
    "english": "english",
    "afemai": "etsako",
    "shona": "shona",
    "eggon": "eggon",
    "luganda and kiswahili": "luganda and kiswahili",
    "ukwuani": "ukwuani",
    "sesotho": "sesotho",
    "benin": "bini",
    "kagoma": "gyong",
    "nasarawa eggon": "eggon",
    "tiv": "tiv",
    "south african english": "south african english",
    "borana": "borana",
    "swahili ,luganda ,arabic": "swahili ,luganda ,arabic",
    "ogoni": "ogoni",
    "mada": "mada",
    "bette": "bette",
    "berom": "berom",
    "bini": "bini",
    "ngas": "ngas",
    "etsako": "etsako",
    "okrika": "okrika",
    "venda": "venda",
    "siswati": "swati",
    "damara": "damara",
    "yoruba, hausa": "yoruba, hausa",
    "southern sotho": "sotho",
    "kanuri": "kanuri",
    "itsekiri": "itsekiri",
    "ekpeye": "ekpeye",
    "mwaghavul": "mwaghavul",
    "bajju": "bajju",
    "luo, swahili": "dholuo, swahili",
    "dholuo": "dholuo",
    "ekene": "ekene",
    "jaba": "jaba",
    "ika": "ika",
    "angas": "ngas",
    "ateso": "ateso",
    "brass": "brass",
    "ikulu": "ikulu",
    "eleme": "eleme",
    "chichewa": "chichewa",
    "oklo": "oklo",
    "meru": "meru",
    "agatu": "agatu",
    "okirika": "kirirke",
    "igarra": "Ebira",
    "ijaw(nembe)": "ijaw",
    "khana": "khana",
    "ogbia": "ogbia",
    "gbagyi": "gbagyi",
    "portuguese": "portuguese",
    "delta": "bini",
    "bassa": "bassa",
    "etche": "etche",
    "kubi": "kubi",
    "jukun": "jukun",
    "igbo and yoruba": "igbo and yoruba",
    "urobo": "urhobo",
    "kalabari": "kalabari",
    "ibani": "ibani",
    "obolo": "obolo",
    "idah": "igala",
    "bassa-nge/nupe": "bassa-nge/nupe",
    "yala mbembe": "mbembe",
    "eket": "ibibio",
    "afo": "afo",
    "ebiobo": "ibiobo",
    "nyandang": "nyandang",
    "ishan": "esan",
    "bagi": "Gbagyi",
    "estako": "etsako",
    "gerawa": "gerawa",
}